repos:
    - repo: https://github.com/timothycrosley/isort
      rev: 5.10.1
      hooks:
        - id: isort
          exclude: ^docs/

    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
        - id: black
          exclude: ^docs/

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
        - id: flake8
          types:
            - python
          exclude: ^docs/

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.961'
      hooks:
      -   id: mypy
          files: dmelon/

