name: build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        mamba-version: "*"
        activate-environment: pstatmodel
        auto-update-conda: false
        python-version: 3.9
        use-only-tar-bz2: true
    - name: Install dependencies
      run: |
        conda env update -f requirements/environment.yml
    - name: Install the Package
      run: |
        pip install -e .
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Codecov
      uses: codecov/codecov-action@v1.0.15
      with:
        verbose: true
